env:
  browser: true
  es2021: true
  jest: true
  node: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  import/no-extraneous-dependencies:
    [
      "error",
      {
        "devDependencies": false,
        "optionalDependencies": false,
        "peerDependencies": false,
      },
    ]
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  fp/no-mutating-methods: ["error", { "allowedObjects": ["_"] }]
